import type { AppConfig } from "./types";

export const defaultAppConfig: AppConfig = {
  version: 1,
  model: {
    provider: "openai-compatible",
    baseUrl: "http://127.0.0.1:1234/v1",
    apiKey: "",
    model: "local-model",
    temperature: 0.8,
    sendTemperature: true,
    maxTokens: 260,
    timeoutMs: 45000,
    visionEnabled: true,
  },
  character: {
    name: "Mika",
    persona: "A warm, witty desktop companion who comments like a good anime watch buddy.",
    tone: "short, playful, observant, never intrusive",
    language: "zh-CN",
  },
  user: {
    name: "你",
    role: "屏幕前的用户",
  },
  prompt: {
    systemTemplate: [
      "You are {{companion.name}}, a desktop danmaku companion.",
      "Persona: {{companion.persona}}",
      "Tone: {{companion.tone}}",
      "Language: {{companion.language}}",
      "You are accompanying {{user.name}} ({{user.role}}).",
      "React to the current screen with brief, specific, non-intrusive danmaku comments.",
      "Return exactly {{requestedCount}} comments unless the model is unable to parse the request.",
      "Do not mention private data, credentials, or exact personal identifiers.",
      "Each comment must be short enough to fit on screen.",
      "Return only JSON in this shape: {{jsonShape}}",
    ].join("\n"),
    userTemplate: "",
  },
  danmaku: {
    fontSize: 22,
    opacity: 0.92,
    speedSeconds: 10,
    maxCommentLength: 50,
    density: 0.6,
    zone: "full",
    palette: ["#31c3a2", "#f59e0b", "#ef476f", "#5b8def", "#f8fafc"],
    shadow: true,
  },
  runtime: {
    enabled: false,
    intervalMinSeconds: 14,
    intervalMaxSeconds: 28,
    intervalSeconds: 18,
    itemsPerCycle: 3,
    itemsMinPerCycle: 1,
    itemsMaxPerCycle: 3,
    maxItemsPerCycle: 3,
    releaseWindowMinSeconds: 6,
    releaseWindowMaxSeconds: 10,
    releaseWindowSeconds: 8,
    captureMaxEdgePixels: 960,
    captureImageFormat: "jpeg",
    captureJpegQuality: 0.82,
    historyRounds: 4,
    historyMode: "reset-on-limit",
    historyIncludeImages: false,
    persistScreenshots: false,
    generationLogLimit: 200,
    privacyBlacklist: [],
  },
};
